// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ad1f6019-1e79-4916-93f4-ed630ec1b952";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSuhuChange();
void onKelembabanChange();
void onPompa1Change();
void onPompa2Change();

float suhu;
CloudRelativeHumidity kelembaban;
bool pompa1;
bool pompa2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(suhu, READWRITE, ON_CHANGE, onSuhuChange);
  ArduinoCloud.addProperty(kelembaban, READWRITE, ON_CHANGE, onKelembabanChange);
  ArduinoCloud.addProperty(pompa1, READWRITE, ON_CHANGE, onPompa1Change);
  ArduinoCloud.addProperty(pompa2, READWRITE, ON_CHANGE, onPompa2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);